services:
  # Backend Service
  - type: web
    name: windsurf-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && python app_render.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000

  # Frontend Service  
  - type: web
    name: windsurf-frontend
    env: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm run preview"
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: VITE_API_URL
        value: https://windsurf-backend.onrender.com/api
